services:
  - type: web
    name: omniqa-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: default
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend.vercel.app
      - key: REDIS_ENABLED
        value: "false"
      - key: AI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-3.8-flash
      - key: SERVICE_API_KEY
        generateValue: true
      - key: SPRING_DATA_REDIS_HOST
        sync: false
      - key: SPRING_DATA_REDIS_PORT
        value: 6379
      - key: GCS_BUCKET_NAME
        value: omniqa-studio-assets
